language: python
sudo: false
dist: bionic

branches:
  only:
    - pr/step1

addons:
  apt:
    packages:
    - check
    - python3-pip

python:
  - "3.6"
  - "pypy3"

install:
  - pip install .[dev]

script:
  - PYTHONPATH=.:$PYTHONPATH ./test-travis.sh
